### ISSUE TITLE
Remove iPad Pro giveaway language on escrow invite form

### ISSUE THREAD

**Issue by dsiglin** [earnnest-greenville/earnnest-website#14]
1) Remove the iPad Pro graphic and sweepstakes rules summary from website.
2) Update the escrow invite form text. [Link to new text](https://www.figma.com/file/EkO358JomnoKpTpq6sWfZD2u/MarketingWebsite__V3?node-id=1357%3A8437)
3) Update the escrow invite form submission state text. [Link to new text](https://www.figma.com/file/EkO358JomnoKpTpq6sWfZD2u/MarketingWebsite__V3?node-id=1357%3A8417)

**Comment by dsiglin** [comment]
@robertgonzales in the new design we are removing the escrow holder first and last name fields. Also we are changing `escrow business name` to `Escrow holder name` and changing button to `send the invitation`.  Thanks.

**Comment by robertgonzales** [comment]
@dsiglin oops, missed that in the design. Just pushed the updates.
