### ISSUE TITLE
Copy for Forms

### ISSUE THREAD

**Issue by maks112v** [earnnest-greenville/earnnest-website#17]
- [ ] Success Messages Copy
- [ ] Error Messages Copy

**Comment by robertgonzales** [comment]
@dsiglin here's the current copy for form submission responses:

`SUCCESS`: Successfully submitted!
`DUPLICATES_DETECTED`: Already signed up!
`INVALID_FIELD`: Invalid submission.
`FIELD_CUSTOM_VALIDATION_EXCEPTION`: Invalid submission.

**Comment by dsiglin** [comment]
`SUCCESS`: Thanks for submitting.
`DUPLICATES_DETECTED`: Thanks for submitting.
`INVALID_FIELD`: Please fix errors before submitting again
`FIELD_CUSTOM_VALIDATION_EXCEPTION`: Please fix errors before submitting again
