### ISSUE TITLE
Salesforce Testing

### ISSUE THREAD

**Issue by robertgonzales** [earnnest-greenville/earnnest-website#19]
- [x] Clear all test data in Salesforce
- [x] Invite Form
  - [x] Submit with new email: inviter@nicer.io, invitee@nicer.io, Nicer Holdings
  - [x] Submit again with same data, different name
  - [x] Confirm Account created for invitee
  - [x] Confirm Contacts created or updated for inviter and invitee
  - [x] Confirm inviter Contact added to Agent campaign and invitee Contact added to Escrow campaign
  - [x] Confirm Hubspot submission
- [x] Agent Pre-Registration Form
  - [x] Submit with new email: agent@nicer.io, Nicer Real Estate
  - [x] Submit again with same data, different name
  - [x] Submit again with email used for another form
  - [x] Confirm Account created for indicated brokerage
  - [x] Confirm Contact created or updated
  - [x] Confirm Contact added to Agent Pre-Registration campaign
  - [x] Confirm Hubspot submission
- [x] Get Demo Form
  - [x] Submit with new email: demo@nicer.io, Nicer Studio
  - [x] Submit again with same email, different name
  - [x] Submit again with email used for another form
  - [x] Confirm Account created for indicated company
  - [x] Confirm Contact created or updated
  - [x] Confirm Contact added to Get Demo campaign
  - [x] Confirm Hubspot submission
- [x] Buyer Guide Form
  - [x] Submit with new email: guide@nicer.io
  - [x] Submit again with same email
  - [x] Submit again with email used for another form
  - [x] Confirm Lead created or Lead/Contact updated
  - [x] Confirm Lead/Contact added to Buyer Guide campaign
  - [x] Confirm Hubspot submission
- [x] Learn More Form
  - [x] Submit with new email: learn@nicer.io
  - [x] Submit again with same email, different name
  - [x] Submit again with email used for another form
  - [x] Confirm Contact created or updated
  - [x] Confirm Contact added to Learn More campaign
  - [x] Confirm Hubspot submission
- [x] Clear all test data in Salesforce
- [x] Clear all test data in Hubspot

**Comment by dsiglin** [comment]
### Invite form
- [ ] When submitting form it doesn't show success state
- [ ] Hubspot is sending, MailChimp is not sending.
Error in console
https://dsc.cloud/19043b/Screen-Shot-2020-03-19-22-00-05.43.jpg
