### ISSUE TITLE
Partner page headers

### ISSUE THREAD

**Issue by dsiglin** [earnnest-greenville/earnnest-website#39]
### Changes to partner page header

- [x] Container element `css-1r8ixvk` change to max-width of 900px instead of normal 730px

- [x] `The power of digital earnest money` header, add 
margin-left: 48px; 
margin-bottom: 32px; 
font-size: 48px;

- [x] `<ul>` containing value props add
margin-left: 48px;

- [x] `<li>` inside add
margin-bottom: 24px;

- [x] `Go digital` button should be 64px high, it's a large button.

- [x] Responsive, I haven't done extensive testing on how this looks when screen is reduced. I did notice that at (max-width: 1200px) the new margin-left should be removed so that content (especially button) doesn't break out of the header "crest".

**Comment by maks112v** [comment]
![Screen Shot 2020-06-26 at 2 43 57 PM](https://user-images.githubusercontent.com/11082252/85890505-794bce80-b7bb-11ea-8823-178eeac74cdb.png)
