### ISSUE TITLE
Escrow holder invite form issue

### ISSUE THREAD

**Issue by dsiglin** [earnnest-greenville/earnnest-website#5]
The escrow holder invite form is not submitting the `escrow business name` to the Lonewolf Agent Leads form (ID: 1fbf47eb-31c2-4eda-9b30-8aef1b2e997f, property name: invited_eh).

**Comment by robertgonzales** [comment]
@dsiglin not sure what's happening there. I just tested it and the company name is submitting:
<img width="1919" alt="Screenshot 2020-01-22 16 58 28" src="https://user-images.githubusercontent.com/7729885/72938216-8eb65b80-3d38-11ea-9a14-ed3207b2e257.png">

That field is also required so I don't think it's just a case of people not entering the company name.

**Comment by dsiglin** [comment]
@robertgonzales That's the `Escrow Holder Invitation` form. The issues is the `Lonewolf Agent Leads` form is not capturing the escrow business name in the `invited_eh` field.

**Comment by robertgonzales** [comment]
Ah, thanks for the pointer. This should be fixed now: 
<img width="785" alt="Screenshot 2020-01-24 10 26 29" src="https://user-images.githubusercontent.com/7729885/73080566-06e56400-3e94-11ea-9cec-0cbca0ba2595.png">
