### ISSUE TITLE
Add iPad giveaway assets back in

### ISSUE THREAD

**Issue by dsiglin** [earnnest-greenville/earnnest-website#8]
We are going to run another iPad giveaway. We will be giving away two iPads. We need to add the iPad giveaway assets and language back. The text will need to be updated. I'lll link to various assets with updated text below:

[iPad graphic with text](https://www.figma.com/file/EkO358JomnoKpTpq6sWfZD2u/MarketingWebsite__V3?node-id=1273%3A7990)

[Invite form submitted state](https://www.figma.com/file/EkO358JomnoKpTpq6sWfZD2u/MarketingWebsite__V3?node-id=1197%3A7505)

[Short disclaimer text](https://www.figma.com/file/EkO358JomnoKpTpq6sWfZD2u/MarketingWebsite__V3?node-id=1273%3A7987)

**Comment by maks112v** [comment]
Does this go just on the partner page? @dsiglin

**Comment by dsiglin** [comment]
Yes just the Partner page

**Comment by dsiglin** [comment]
@maks112v I just noticed the form defaults to the submitted state.

**Comment by dsiglin** [comment]
@maks112v I noticed besides the comment above I also noticed there's a double asterisk at the end of `As a thank you for spreading the word about Earnnest, when you invite your escrow holder you are automatically entered into our Earnnest sweepstakes to win one of two iPad Pros`
